# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 140390d77ff9483c0c090773c5ef9473580a4b072eab3d15dc51381465ccb9f461f0608d068e924a491437e8f2c12f983767e35de90b88867f933c75a4a58c71

test:
  secret_key_base: 977119b1d51db73ee4be0068766918c3d97a4d875aa658c40be79f457f9adb5ec8afb0c390caaf9f045b0b75d17ecbb1958ad582222d0eeca6ddbf0e2be2a7cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
